#**Assignment (WC #3 Feature Engineering)**
##Tips Pengerjaan :

1. Klik file > save a copy in drive untuk menyalin notebook ini
2. Kerjakan soal di placeholder yang sudah ditentukan
3. Coba untuk tidak menggunakan AI dulu, pelajari materi yang sudah diberikan
4. Rename file notebook dengan format "WC#3_Nama_Group", contoh "WC#3_Rifan Nashir_Group 3" dan dengan format ".ipynb"

##Ini untuk datasetnyaa yaaa

In [27]:
# Run Code ini Terlebih dahulu agar datasetnya muncul
import pandas as pd

data = {
    'Merek': ['Asus', 'Lenovo', 'Acer', 'Asus', 'Lenovo'], # Untuk One-Hot
    'Kelas': ['Entry-Level', 'Flagship', 'Entry-Level', 'Flagship', 'Mid-Range'], # Untuk Ordinal
    'RAM': ['8 GB', '16 GB ', '4GB', '32 GB', ' 8 GB'],
    'Harga': ['Rp 7.500.000', 'Rp 15.000.000', 'Rp 5.000.000', 'Rp 25.000.000', 'Rp 8.000.000'],
    'Tanggal_Rilis': ['2023-05-12', '2024-01-20', '2022-11-15', '2024-03-10', '2023-08-05']
}
df = pd.DataFrame(data)
display(df)

    Merek        Kelas     RAM          Harga Tanggal_Rilis
0    Asus  Entry-Level    8 GB   Rp 7.500.000    2023-05-12
1  Lenovo     Flagship  16 GB   Rp 15.000.000    2024-01-20
2    Acer  Entry-Level     4GB   Rp 5.000.000    2022-11-15
3    Asus     Flagship   32 GB  Rp 25.000.000    2024-03-10
4  Lenovo    Mid-Range    8 GB   Rp 8.000.000    2023-08-05

### Langkah 1: Data Cleaning 🧹
Mesin tidak bisa menghitung teks "Rp" atau huruf "GB".
**Tugasmu:**
1. Gunakan `.str.replace()` untuk menghapus kata 'Rp ' pada kolom Harga, lalu ubah tipe datanya menjadi integer (`astype(int)`).
2. Hapus kata 'GB' dan spasi pada kolom RAM, lalu ubah menjadi integer.

In [28]:

df['Harga'] = df['Harga'].str.replace('Rp ', '').str.replace('.', '').astype(int)
df['RAM'] = df['RAM'].str.replace('GB', '').str.strip().astype(int)

print(df.info()) # Cek tipe datanya, harusnya sudah int64
display(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Merek          5 non-null      object
 1   Kelas          5 non-null      object
 2   RAM            5 non-null      int64
 3   Harga          5 non-null      int64
 4   Tanggal_Rilis  5 non-null      object
dtypes: int64(2), object(3)
memory usage: 332.0+ bytes
None

    Merek        Kelas  RAM     Harga Tanggal_Rilis
0    Asus  Entry-Level    8   7500000    2023-05-12
1  Lenovo     Flagship   16  15000000    2024-01-20
2    Acer  Entry-Level    4   5000000    2022-11-15
3    Asus     Flagship   32  25000000    2024-03-10
4  Lenovo    Mid-Range    8   8000000    2023-08-05

### Langkah 2: Feature Extraction ✂️
Format tanggal penuh (YYYY-MM-DD) terlalu rumit untuk model sederhana.
**Tugasmu:**
 Ekstrak 4 digit pertama (Tahun) dari kolom `Tanggal_Rilis` menggunakan teknik *slicing* `.str[:4]`. Simpan ke dalam kolom baru bernama `Tahun_Rilis`, lalu ubah jadi integer!

In [29]:
df['Tanggal_Rilis'] = df['Tanggal_Rilis'].astype(str).str[:4].astype(int)
print(df.info)

<bound method DataFrame.info of     Merek        Kelas  RAM     Harga  Tanggal_Rilis
0    Asus  Entry-Level    8   7500000           2023
1  Lenovo     Flagship   16  15000000           2024
2    Acer  Entry-Level    4   5000000           2022
3    Asus     Flagship   32  25000000           2024
4  Lenovo    Mid-Range    8   8000000           2023>

### Langkah 3: Feature Encoding 🔠 -> 🔢
Algoritma butuh angka, bukan teks seperti "Asus" atau "Lenovo".
**Tugasmu:** Gunakan Encoding untuk mengubah kolom `Merek dan Kelas` menjadi kolom-kolom baru berisi angka

In [30]:
merek_enc = pd.get_dummies(df['Merek'], prefix='Merek')
df = pd.concat([df, merek_enc], axis=1)
print(df)

    Merek        Kelas  RAM     Harga  Tanggal_Rilis  Merek_Acer  Merek_Asus  \
0    Asus  Entry-Level    8   7500000           2023       False        True
1  Lenovo     Flagship   16  15000000           2024       False       False
2    Acer  Entry-Level    4   5000000           2022        True       False
3    Asus     Flagship   32  25000000           2024       False        True
4  Lenovo    Mid-Range    8   8000000           2023       False       False

   Merek_Lenovo
0         False
1          True
2         False
3         False
4          True

In [31]:
df['Kelas'] = df['Kelas'].astype(str).str.strip()
mapping_kelas_king = {'Entry-Level': 1, 'Flagship': 3, 'Mid-Range': 2}
df['Kelas_Encoded'] = df['Kelas'].map(mapping_kelas_king)

print("Isi unik kolom Kelas:", df['Kelas_Encoded'].unique())
display(df.head())

Isi unik kolom Kelas: [1 3 2]

,Merek,Kelas,RAM,Harga,Tanggal_Rilis,Merek_Acer,Merek_Asus,Merek_Lenovo,Kelas_Encoded
0,Asus,Entry-Level,8,7500000,2023,False,True,False,1
1,Lenovo,Flagship,16,15000000,2024,False,False,True,3
2,Acer,Entry-Level,4,5000000,2022,True,False,False,1
3,Asus,Flagship,32,25000000,2024,False,True,False,3
4,Lenovo,Mid-Range,8,8000000,2023,False,False,True,2

### Langkah 4: Train-Test Split 🪓
**PERHATIAN:** Sebelum melakukan *Scaling*, kita WAJIB membagi data menjadi Data Latih (Train) dan Data Uji (Test) untuk menghindari *Data Leakage* (kebocoran informasi).

**Tugasmu:**
Pisahkan fitur (X) dan target (y), lalu bagi data dengan rasio 80:20 menggunakan `train_test_split`.

In [32]:
from sklearn.model_selection import train_test_split
X = df.drop(columns=['Harga'])
y = df['Harga']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Kolom di X (Fitur):", X.columns.tolist())
print("Isi y (Target):", y.name)

Kolom di X (Fitur): ['Merek', 'Kelas', 'RAM', 'Tanggal_Rilis', 'Merek_Acer', 'Merek_Asus', 'Merek_Lenovo', 'Kelas_Encoded']
Isi y (Target): Harga

### Langkah 5: Feature Scaling (Awas Jangan Semua Kolom!) ⚖️
Ingat, kita **HANYA** perlu melakukan scaling pada data numerik asli seperti `RAM` dan `Tahun_Rilis`.
Data hasil *Encoding* (merek dan kelas) yang isinya sudah 0, 1, atau 2 tidak perlu di-scale lagi!

**Tugasmu:** Gunakan `MinMaxScaler` atau `StandardScaler` HANYA untuk kolom `RAM` dan `Tahun_Rilis`.

In [33]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
cols_to_scale = ['RAM', 'Tanggal_Rilis']
X_train[cols_to_scale] = scaler.fit_transform(X_train[cols_to_scale])

X_test[cols_to_scale] = scaler.transform(X_test[cols_to_scale])
display(X_train.head())

,Merek,Kelas,RAM,Tanggal_Rilis,Merek_Acer,Merek_Asus,Merek_Lenovo,Kelas_Encoded
4,Lenovo,Mid-Range,-0.450835,0.000000,False,False,True,2
2,Acer,Entry-Level,-0.811503,-1.414214,True,False,False,1
0,Asus,Entry-Level,-0.450835,0.000000,False,True,False,1
3,Asus,Flagship,1.713172,1.414214,False,True,False,3